### ISSUE TITLE
Replacement for context method

### ISSUE THREAD

**Issue by jolora** [stuartcusackie/statamic-blade-view-data#1]
Thanks for sharing this package @stuartcusackie. It was the quickest solution I could see for using SeoPro with a blade component layout, like this:

```
@if(\StatData::context())
  @seo_pro('meta', \StatData::context())
@endif
```

It worked perfectly.

Your updates yesterday removed `context()`. I was wondering if you'd mind sharing how I can pass the necessary data into the seo_pro blade directive moving forward please?

**Comment by stuartcusackie** [comment]
My apologies. I didn't think anybody was using this package and I meant to mark it as pre-release.

I have restored the context() method now (I have no idea why I removed it). Let me know if you are still having trouble with it.

By the way, I removed the config file yesterday and I'm using a new method. You can delete your config file for this package if you have one.
